version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000" 
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://bhailumandaliya11:pg7xs66ptzkra9wN@cluster0.8x6228x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/notification-setup
      JWT_SECRET: 256713
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    
      - "15673:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  rabbitmq-data:
    driver: local

networks:
  default:
    driver: bridge
